<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_category_banner_image</name>
   <tag></tag>
   <elementGuidId>4c9dae6c-2844-4f0c-9fc5-3cc57f419fc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.category_banner_image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5f22fb9b-6092-4043-be4f-7072f12b2c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/09/handmade_furnitures2.webp</value>
      <webElementGuid>aac587fa-ce90-4dfb-b4c4-53e0a3df0631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_banner_image</value>
      <webElementGuid>634a924a-0c5b-45d0-a617-c1d290194508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;col-full&quot;]/div[@class=&quot;wbm_banner_image banner&quot;]/img[@class=&quot;category_banner_image&quot;]</value>
      <webElementGuid>72210d2a-5ee4-46c3-8ecc-3e2d23ece750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/img</value>
      <webElementGuid>ef6b49f6-4756-447c-86de-9acf9a72721b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/09/handmade_furnitures2.webp')]</value>
      <webElementGuid>f2b7baa2-febe-420d-b609-be2e89a21089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>6ceabb0e-f9e3-4e56-9d8c-1ab74fcc19da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/09/handmade_furnitures2.webp']</value>
      <webElementGuid>e2afafb9-128e-44fd-aa12-50d3e6bb30da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
