<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-woocommerce_thumbnail size-w_8f6098</name>
   <tag></tag>
   <elementGuidId>e9788663-0788-4b9e-83cd-952053a5a2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[11]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-328.status-publish.instock.product_cat-photo-frame.product_cat-under-500.has-post-thumbnail.taxable.shipping-taxable.product-type-variable > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02a8fb8b-0208-45d8-bea8-8988f2f35f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>9f7bc241-abfd-4e25-9bc6-173538ba1b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>f275c9fb-b2e0-4ec0-9f8b-940f1d1412d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-324x324.jpg</value>
      <webElementGuid>5899720d-b99d-49a5-a598-6722d85e1869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>8f1cc402-5c26-4f98-8812-cc5484291fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>23f71d9a-83c5-4f05-aa66-e6f0bc848ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>df024926-f44e-43ef-8a21-c38adf11e121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-324x324.jpg 324w, https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-100x100.jpg 100w, https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-416x416.jpg 416w, https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-300x300.jpg 300w, https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-150x150.jpg 150w, https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1.jpg 600w</value>
      <webElementGuid>a3126860-4a32-46ac-bda7-35f5f8cb797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>b1172366-b34e-4f3c-80f0-3835515061b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-328 status-publish instock product_cat-photo-frame product_cat-under-500 has-post-thumbnail taxable shipping-taxable product-type-variable&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>69e75695-3b22-4e63-953a-87cf7352d2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[11]/a/img</value>
      <webElementGuid>7c544fd7-c32c-40d4-8b8e-a566d0b4949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-324x324.jpg')]</value>
      <webElementGuid>f0e54f95-5404-4302-99bf-bd846a33a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a/img</value>
      <webElementGuid>f2f96894-7894-4ac5-8c2d-7a31bf7b2fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/08/hd-286blue-a_1-324x324.jpg']</value>
      <webElementGuid>14b03dd8-3c52-4817-b91b-0cb46f914768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
