<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cane Baskets</name>
   <tag></tag>
   <elementGuidId>dcee3ae8-f852-4097-b48b-b1dbd394af60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26673']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26673 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04b3e960-fea4-47e4-875a-67144b555990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/cane-fruit-baskets/</value>
      <webElementGuid>65ae0432-88bf-43e0-a0c6-07e2e40297cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cane Baskets</value>
      <webElementGuid>7518bcf3-44fa-4faa-99eb-2460e90b6f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26673&quot;)/a[1]</value>
      <webElementGuid>266b4b5e-5b71-45d3-9128-02d5a704b6b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26673']/a</value>
      <webElementGuid>aba3532e-88fc-455e-b1cf-4ec26a7b87ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cane Baskets')]</value>
      <webElementGuid>0eb58605-6871-4a93-af7c-1cd973b18de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/cane-fruit-baskets/')]</value>
      <webElementGuid>f23adbd6-7e6b-43cf-938e-09bb53858467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[6]/a</value>
      <webElementGuid>53d0c1c7-e6ae-4d38-9cf9-4cc2c4c652b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/cane-fruit-baskets/' and (text() = 'Cane Baskets' or . = 'Cane Baskets')]</value>
      <webElementGuid>a4cd75e7-0dea-4fbb-8c2f-43af6ee4ca66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
