<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Handmade Furnitures</name>
   <tag></tag>
   <elementGuidId>d92fc1df-e82b-43cf-97d9-68e775aa4405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26660']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26660 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ee67b08-1409-46a1-b369-bad307eae632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/handmade-furnitures/</value>
      <webElementGuid>367368c4-3377-4419-8266-62087fc44a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>4e8a10f1-3785-493c-93dc-5c1c224de575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Handmade Furnitures</value>
      <webElementGuid>d1bb8174-c15e-447b-91d9-b6b755044d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26660&quot;)/a[1]</value>
      <webElementGuid>65433e5c-a84f-42da-a191-ccdc414aa8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26660']/a</value>
      <webElementGuid>645fa608-2160-4639-b2d6-e563e40a414b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Handmade Furnitures')]</value>
      <webElementGuid>9369e14e-261a-4f8e-963f-224c6f9c96f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/handmade-furnitures/')]</value>
      <webElementGuid>0286b471-d372-4595-978e-de7255e5e3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/nav/div/ul/li[2]/a</value>
      <webElementGuid>640e479e-4ccd-46e3-b570-89fc8900ddf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/handmade-furnitures/' and (text() = 'Handmade Furnitures' or . = 'Handmade Furnitures')]</value>
      <webElementGuid>a6f7353c-408d-4041-b4a7-6e163dc0d6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
