<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Iron Stools Frame</name>
   <tag></tag>
   <elementGuidId>0f352999-da82-441f-821c-f3d779e5fbc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26671']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26671 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>802dc386-de80-4664-8fe1-3d45ae3beb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/iron-stools-frame/</value>
      <webElementGuid>365c63d7-6ed2-4ba0-a0f1-42e4512f25bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iron Stools Frame</value>
      <webElementGuid>78e8af65-1e30-4486-beb1-9080d7951674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26671&quot;)/a[1]</value>
      <webElementGuid>9571ca66-c12c-40b8-9249-926919901bdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26671']/a</value>
      <webElementGuid>105cd4d1-b4f8-4450-a937-9f3f98ad872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Iron Stools Frame')]</value>
      <webElementGuid>ef2f0e33-3218-4431-bf91-c069573ee5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/iron-stools-frame/')]</value>
      <webElementGuid>2089f180-4a1b-4e60-9e82-2581823c24c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[5]/a</value>
      <webElementGuid>5af701fa-2b4b-47e7-8e47-5a26c8b70105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/iron-stools-frame/' and (text() = 'Iron Stools Frame' or . = 'Iron Stools Frame')]</value>
      <webElementGuid>a7c132c1-32f8-4407-910d-817d96b770eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
