<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Natural Mudha</name>
   <tag></tag>
   <elementGuidId>1f513579-163e-46b0-8197-e07c07ebd2bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26668']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26668 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>175e981c-6578-4d78-ae2b-d4733d7bc3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/natural-mudha/</value>
      <webElementGuid>44d9ee0b-c7bd-4dcc-9a65-a8cd3450f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Natural Mudha</value>
      <webElementGuid>e746f190-0006-4f73-a049-c51abd6e909a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26668&quot;)/a[1]</value>
      <webElementGuid>a4f59912-3aae-4eec-aa88-1bec38d007fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26668']/a</value>
      <webElementGuid>11bff857-decd-49a7-9b66-b29cd50545c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Natural Mudha')]</value>
      <webElementGuid>35c36d9f-3a2c-4566-8817-ef54363bc76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/natural-mudha/')]</value>
      <webElementGuid>dc22a86b-cca8-4f22-b77e-0d8577335e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>950205c1-00ae-4359-8a27-83d5835c225d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/natural-mudha/' and (text() = 'Natural Mudha' or . = 'Natural Mudha')]</value>
      <webElementGuid>fcf64f76-90ca-43a0-a3c0-39617675ff64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
