<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wooden Furnitures</name>
   <tag></tag>
   <elementGuidId>0c93eab4-3b59-4525-903d-8f3305fedf0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26675']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26675 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae602453-7298-45c1-8d73-3605f4cec264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/wooden-furnitures/</value>
      <webElementGuid>04913cae-9d42-4cba-9df2-0091000844b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wooden Furnitures</value>
      <webElementGuid>522b11ed-7155-4e74-9c0a-99b46ee6ee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26675&quot;)/a[1]</value>
      <webElementGuid>cd85febe-5e2c-47ce-a618-5a8fdd517428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26675']/a</value>
      <webElementGuid>88a8a5ee-acb5-4731-a516-f5d215704b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wooden Furnitures')]</value>
      <webElementGuid>f2e8936b-32e5-4385-9c2b-11c67cb7c340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/wooden-furnitures/')]</value>
      <webElementGuid>9d0189fe-0485-4072-b181-4cb8ff5a104d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[8]/a</value>
      <webElementGuid>8357694b-4ce1-4941-b34f-124983dd4918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/wooden-furnitures/' and (text() = 'Wooden Furnitures' or . = 'Wooden Furnitures')]</value>
      <webElementGuid>e88fb0a6-cb7c-4d39-86cd-ea8724ad070f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
