<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wooden Charpai Pidha Stool</name>
   <tag></tag>
   <elementGuidId>8688db02-8b38-4acc-9a39-5f8a447a00f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26670']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26670 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0d7d200-961e-4ec1-a60c-d70fbdd33ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/pidha-stools/</value>
      <webElementGuid>c081c6b5-ed10-4f1f-aee2-2b01dd0ad140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wooden Charpai Pidha Stool</value>
      <webElementGuid>eda89bbc-9ff6-4459-ac5f-9feec1319a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26670&quot;)/a[1]</value>
      <webElementGuid>cbd8deff-e6fc-42c5-84c9-4526e9f5fbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26670']/a</value>
      <webElementGuid>69767bb5-5073-40e8-bc48-48a4ef985f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wooden Charpai Pidha Stool')]</value>
      <webElementGuid>5275cfd1-f505-4ccb-a834-e651803907e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/pidha-stools/')]</value>
      <webElementGuid>3c1b2bf2-e75d-4914-9052-44700aed9c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[4]/a</value>
      <webElementGuid>d7a6dc44-100d-4281-825d-2d72092995c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/pidha-stools/' and (text() = 'Wooden Charpai Pidha Stool' or . = 'Wooden Charpai Pidha Stool')]</value>
      <webElementGuid>7afe6ae6-4803-4d07-bc25-cab653ddae54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
