<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-woocommerce_thumbnail size-w_8f6098</name>
   <tag></tag>
   <elementGuidId>9ed0a807-3f28-44b3-b97a-a83563fd82cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.product.type-product.post-28312.status-publish.instock.product_cat-key-holders.has-post-thumbnail.taxable.shipping-taxable.purchasable.product-type-simple > a.woocommerce-LoopProduct-link.woocommerce-loop-product__link > img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ea86af9-c7be-419c-8b77-e70e9b69416c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>e2045677-bc58-4206-88d0-dc89efce9b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>46cb5f11-c11a-4bb8-a5a1-0ef0df397e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-312B-324x324.jpg?v=1704352318</value>
      <webElementGuid>c4cc9af6-5453-4cfa-9a90-936f282e7d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>77c9165f-16cb-471a-8eb9-afe44ce35658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b295845e-9722-4c58-9a3d-f166955d1756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/HD-312B-324x324.jpg?v=1704352318 324w, https://craferia.com/wp-content/uploads/2024/01/HD-312B-150x150.jpg?v=1704352318 150w, https://craferia.com/wp-content/uploads/2024/01/HD-312B-100x100.jpg?v=1704352318 100w</value>
      <webElementGuid>fe9802a3-050b-44a5-aae1-8310dad024d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>17dc1754-aa2c-42d8-83de-cc4eacb63ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-28312 status-publish instock product_cat-key-holders has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>79722c6a-ccaf-4e3a-9557-30c8455557a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li[2]/a/img</value>
      <webElementGuid>73b92463-294f-4802-a9e0-78ead9fc94ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://craferia.com/wp-content/uploads/2024/01/HD-312B-324x324.jpg?v=1704352318')])[2]</value>
      <webElementGuid>c994e04c-4397-4a11-b93e-21c132066b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>8b4be273-dc46-4475-b470-64e2d00d4b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/HD-312B-324x324.jpg?v=1704352318']</value>
      <webElementGuid>64e2b8eb-f9ba-4789-859d-e7956cd71b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
