<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_attachment-woocommerce_thumbnail size-w_8f6098</name>
   <tag></tag>
   <elementGuidId>3df15bbe-1fd4-4a8d-b704-e137c76de62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/ul/li/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.attachment-woocommerce_thumbnail.size-woocommerce_thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2c0d6157-7496-40c9-b463-0499af444f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>832066d5-2343-4b86-86a9-7276908ad0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>324</value>
      <webElementGuid>62401c51-0d58-4564-8e6a-4e37bd549060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-324x324.jpeg?v=1708846323</value>
      <webElementGuid>a9f9efc0-ea35-4d2c-986d-f17d907aee74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-woocommerce_thumbnail size-woocommerce_thumbnail</value>
      <webElementGuid>8a0420b1-d366-4ee1-93dc-a233cf618a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>20379728-e2ec-48db-868a-c2999decd5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>ad354ff9-4217-4938-be9c-5ed40c0c81d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-324x324.jpeg?v=1708846323 324w, https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-100x100.jpeg?v=1708846323 100w, https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-150x150.jpeg?v=1708846323 150w</value>
      <webElementGuid>b8fc3569-aac7-45af-84af-d6b1c018b959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 324px) 100vw, 324px</value>
      <webElementGuid>a87788a6-34d5-442b-8103-3a68033e1898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/ul[@class=&quot;products columns-4&quot;]/li[@class=&quot;product type-product post-29568 status-publish first instock product_cat-handmade-furnitures product_cat-pidha-stools has-post-thumbnail taxable shipping-taxable purchasable product-type-simple&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/img[@class=&quot;attachment-woocommerce_thumbnail size-woocommerce_thumbnail&quot;]</value>
      <webElementGuid>fe47a194-5a9d-4c73-8105-9b0bd35b05d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/ul/li/a/img</value>
      <webElementGuid>c1cfa929-476f-423d-abf4-f1d63c085a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-324x324.jpeg?v=1708846323')]</value>
      <webElementGuid>8b2da941-84ad-4f1c-a5e9-7dfd41aa2e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>dbb3e7fd-0f50-41b4-ad02-71ca268def31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2024/01/WhatsApp-Image-2024-01-31-at-10.54.15-324x324.jpeg?v=1708846323']</value>
      <webElementGuid>08db0bb3-7ca4-4891-b679-75162dc630ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
