<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bamboo Furniture</name>
   <tag></tag>
   <elementGuidId>2cd15920-11e6-4b4a-aaa5-24ebe20fac46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26661']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26661 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc6f2211-3edf-44ff-9302-61821e8dc010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/bamboo-furniture/</value>
      <webElementGuid>dc2c71db-cb2f-4ac2-9cb3-92f779fa7e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo Furniture</value>
      <webElementGuid>80d7cda2-c572-4130-9f6e-3cb6915b1936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26661&quot;)/a[1]</value>
      <webElementGuid>dd28e6f2-a8d9-488c-87dd-6e8aa548359a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26661']/a</value>
      <webElementGuid>3efb4c06-9cd0-4dc4-b61c-62e0aa631b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bamboo Furniture')]</value>
      <webElementGuid>53d5a91f-e74d-4fc2-9f1c-c1bd70b84b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/bamboo-furniture/')]</value>
      <webElementGuid>11b8e202-f833-46d5-a83c-4efb5dfafc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>942fede1-d0df-4ca3-bd7b-29ef603adf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/bamboo-furniture/' and (text() = 'Bamboo Furniture' or . = 'Bamboo Furniture')]</value>
      <webElementGuid>1ac9376c-cef9-48f1-a95a-c2c73ae5ae5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
