<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bamboo is a highly sustainable material t_882103</name>
   <tag></tag>
   <elementGuidId>3c08bd05-7251-480c-8d79-6b507d5eb1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/header/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.term-description > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4ee76870-eac3-495b-9923-cbd0e176e76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bamboo is a highly sustainable material that grows quickly, making it an eco-friendly choice for furniture. Bamboo furniture is becoming increasingly popular due to its unique and natural appearance. Bamboo cane furniture is also popular for its durability and strength.Bamboo furniture sets come in a variety of styles and designs that can add a touch of elegance to any room. From sleek and modern designs to more traditional looks, there is a bamboo furniture set available to fit any aesthetic.</value>
      <webElementGuid>99baa96b-026f-4459-ad3d-676feae138aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/header[@class=&quot;woocommerce-products-header&quot;]/div[@class=&quot;term-description&quot;]/p[1]</value>
      <webElementGuid>a8e5f340-8dec-453e-8e46-539e4a1fa4f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/header/div/p</value>
      <webElementGuid>92a02fe1-0cb5-4ea6-b6d0-38707ba25e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/p</value>
      <webElementGuid>29617b76-4fbd-4bbb-91be-d724243df583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Bamboo is a highly sustainable material that grows quickly, making it an eco-friendly choice for furniture. Bamboo furniture is becoming increasingly popular due to its unique and natural appearance. Bamboo cane furniture is also popular for its durability and strength.Bamboo furniture sets come in a variety of styles and designs that can add a touch of elegance to any room. From sleek and modern designs to more traditional looks, there is a bamboo furniture set available to fit any aesthetic.' or . = 'Bamboo is a highly sustainable material that grows quickly, making it an eco-friendly choice for furniture. Bamboo furniture is becoming increasingly popular due to its unique and natural appearance. Bamboo cane furniture is also popular for its durability and strength.Bamboo furniture sets come in a variety of styles and designs that can add a touch of elegance to any room. From sleek and modern designs to more traditional looks, there is a bamboo furniture set available to fit any aesthetic.')]</value>
      <webElementGuid>7b5d5154-ca75-4068-8329-be6f1a046714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
