<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clock</name>
   <tag></tag>
   <elementGuidId>592b5f8b-4905-4f49-8083-89942064666a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26695']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26695 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>110d0db8-827c-4d9f-ba03-de850c50717c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/clock/</value>
      <webElementGuid>d6284306-1b97-4b12-b8ba-ce4c032e68eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clock</value>
      <webElementGuid>6897774f-f294-4b2a-9b5b-39c4778d2e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26695&quot;)/a[1]</value>
      <webElementGuid>a18c1f16-3bed-4c97-b198-5ecb9df1291c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26695']/a</value>
      <webElementGuid>887fcbe2-5412-45ef-9384-e9c10b61a311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Clock')]</value>
      <webElementGuid>5c209128-03b2-4980-bbe0-d55bd479815b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/clock/')]</value>
      <webElementGuid>c29cb8fe-d321-47b6-a4fe-2c83a6b83727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[5]/a</value>
      <webElementGuid>f64b8b9f-1b6c-43e8-9957-7fb62b5b09e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/clock/' and (text() = 'Clock' or . = 'Clock')]</value>
      <webElementGuid>bb4b687c-7c14-490d-abb0-806e660234a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
