<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home Accents</name>
   <tag></tag>
   <elementGuidId>606c7012-3fa1-44fd-83a9-9275b2055e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26691']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26691 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f3e87de-18e0-4453-8f71-3e2146e4deab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/home-accents/</value>
      <webElementGuid>758ed10a-388e-41d8-b12c-632d87bd8b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home Accents</value>
      <webElementGuid>d20b1b5f-03c5-4171-84a2-fdc3b4c819a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26691&quot;)/a[1]</value>
      <webElementGuid>2b06361e-d94b-458e-b653-57b7b028db2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26691']/a</value>
      <webElementGuid>8d54a200-9b59-495b-9f34-9d97c6e58d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Home Accents')]</value>
      <webElementGuid>1a15064a-6d2c-4232-97f5-44aa0bd6c126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/home-accents/')]</value>
      <webElementGuid>69d24abc-3d93-4448-ada6-e2ecf82e71ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a</value>
      <webElementGuid>305c202a-150f-4be5-9e7f-ed88834196cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/home-accents/' and (text() = 'Home Accents' or . = 'Home Accents')]</value>
      <webElementGuid>16ae42a2-fe08-41bd-b718-312699e2d405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
