<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Key Holders</name>
   <tag></tag>
   <elementGuidId>9278f0d5-35a6-434a-9ee4-574614a8af8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26696']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26696 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40c8c1e3-e952-49de-ab37-e6b7e698a419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/key-holders/</value>
      <webElementGuid>d58a1ff8-f769-4b05-ac48-411ab3dd7b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key Holders</value>
      <webElementGuid>2a506ae9-4dfd-45cd-8e41-795578a5efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26696&quot;)/a[1]</value>
      <webElementGuid>55da78a9-66c0-4055-9938-2d5633e92a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26696']/a</value>
      <webElementGuid>a0b4a1b2-7324-48c1-8ee1-e051e2d1450f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Key Holders')]</value>
      <webElementGuid>83004456-b946-4337-8279-d6d8ff79e5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/key-holders/')]</value>
      <webElementGuid>e2c099de-25ff-46b9-b39f-a89300efcab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[6]/a</value>
      <webElementGuid>0dadeab3-54a5-4c09-ab31-e3048c3cea15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/key-holders/' and (text() = 'Key Holders' or . = 'Key Holders')]</value>
      <webElementGuid>371c1261-1735-41d2-86c0-5a1491e272b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
