<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lamps  Lightings</name>
   <tag></tag>
   <elementGuidId>a83ba162-007e-4df0-b92e-89fd3ea25a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26694']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26694 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>926fa954-6e44-49c0-bba0-b20453420ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/lamps-lightings/</value>
      <webElementGuid>03ea5703-2032-4e46-a008-96d3735b3332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lamps &amp; Lightings</value>
      <webElementGuid>d4c1e720-3b46-4b31-869f-f43f9da955c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26694&quot;)/a[1]</value>
      <webElementGuid>f9152591-5251-46a6-85a3-8398f077ec56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26694']/a</value>
      <webElementGuid>30cd68b6-c3ef-4099-baab-3df16f5654d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lamps &amp; Lightings')]</value>
      <webElementGuid>fecda72a-75ec-49eb-b404-4b92db25eade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/lamps-lightings/')]</value>
      <webElementGuid>bcc74500-d127-48b9-9e88-6369ba0935ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[4]/a</value>
      <webElementGuid>2a8130ba-06da-4a5c-b8a9-4f465d6e1efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/lamps-lightings/' and (text() = 'Lamps &amp; Lightings' or . = 'Lamps &amp; Lightings')]</value>
      <webElementGuid>4ae7bef0-0213-47af-8d69-7b90e4a3fbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
