<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wall Decor</name>
   <tag></tag>
   <elementGuidId>6c6c94fc-07f4-4d90-ad7e-6612a37dd448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-26685']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-26685 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e940a5d-a4cf-4f68-bf7d-d0420a60d6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://craferia.com/wall-decor/</value>
      <webElementGuid>44a94bc5-dc97-49b6-9ad7-850fce2460c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wall Decor</value>
      <webElementGuid>daa2ee09-b6c2-4beb-ab59-74f2f6c40187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-26685&quot;)/a[1]</value>
      <webElementGuid>f83cb391-a3d0-4c35-92c1-ad0f9cdfeb64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-26685']/a</value>
      <webElementGuid>1fd41f17-ce5d-4d59-ace9-81cfd21d93b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wall Decor')]</value>
      <webElementGuid>62e70fc4-7095-4ac8-ad6d-8878cdfb8fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://craferia.com/wall-decor/')]</value>
      <webElementGuid>3b486bef-5370-484d-8793-ecf712a93627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[2]/a</value>
      <webElementGuid>aa63d69b-ea92-4ecc-a3a2-f6a0d737941a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://craferia.com/wall-decor/' and (text() = 'Wall Decor' or . = 'Wall Decor')]</value>
      <webElementGuid>a692ce73-9395-4518-a06e-a88e5007dd98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
